services:
  - type: web
    name: tts-api
    env: python
    buildCommand: pip install -r tts_api/requirements.txt
    startCommand: cd tts_api && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CHECKPOINT_PATH
        value: "/opt/render/project/src/ckpt/checkpoint_step500000.pth"